<a href="https://colab.research.google.com/github/Hanifanta/Capstone_RECCOFFEE/blob/Anas/reccoffee_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Import Library**

In [1]:
# Data loading and data analysis
import numpy as np
import pandas as pd
import json
import zipfile
from google.colab import files

# Data visualization
import matplotlib.pyplot as plt

# Data preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

# Splitting data
from sklearn.model_selection import train_test_split

# Modelling
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
coffee = pd.read_csv('coffee.csv')
coffee.head(5)

,all_text,name,rating,roaster,slug,region_africa_arabia,region_caribbean,region_central_america,region_hawaii,region_asia_pacific,...,aroma,acid,body,flavor,aftertaste,with_milk,desc_1,desc_2,desc_3,desc_4
0,\n\n\n\n \n93\nFlight Coffee Co.\nEthiopia Der...,Ethiopia Deri Kochoha,93,Flight Coffee Co.,/review/ethiopia-deri-kochoha-2,1,0,0,0,0,...,9.0,8.0,9.0,9.0,8.0,NaN,"Bright, crisp, sweetly tart. Citrus medley, ca...",From the Deri Kochoha mill in the Hagere Marya...,A poised and melodic wet-processed Ethiopia co...,NaN
1,\n\n\n\n\n91\nDoi Chaang Coffee\nEspresso\nLoc...,Espresso,91,Doi Chaang Coffee,/review/espresso-14,0,0,0,0,1,...,8.0,NaN,8.0,8.0,8.0,9.0,"Evaluated as espresso. Deeply rich, sweetly ro...",Doi Chaang is a single-estate coffee produced ...,"A rich, resonant espresso from Thailand, espec...",NaN
2,\n\n\n\n \n95\nTemple Coffee and Tea\nKenya Ru...,Kenya Ruthaka Peaberry,95,Temple Coffee and Tea,/review/kenya-ruthaka-peaberry,1,0,0,0,0,...,9.0,8.0,9.0,10.0,8.0,NaN,"Deeply sweet, richly savory. Dark chocolate, p...",Despite challenges ranging from contested gove...,"A high-toned, nuanced Kenya cup, classic in it...",NaN
3,\n\n\n\n \n93\nTemple Coffee and Tea\nEthiopia...,Ethiopia Gora Kone Sidamo,93,Temple Coffee and Tea,/review/ethiopia-gora-kone-sidamo,1,0,0,0,0,...,9.0,8.0,9.0,9.0,8.0,NaN,"Fruit-forward, richly chocolaty. Raspberry cou...",Southern Ethiopia coffees like this one are la...,"A playful, unrestrained fruit bomb of a coffee...",NaN
4,\n\n\n\n\n93\nChoosy Gourmet\nSpecialty Coffee...,Specialty Coffee Blend Espresso,93,Choosy Gourmet,/review/specialty-coffee-blend-espresso,0,0,0,0,0,...,9.0,NaN,8.0,9.0,8.0,9.0,"Evaluated as espresso. Rich, chocolaty, sweetl...",A blend of coffees from Ethiopia (natural-proc...,An espresso blend in which spice notes â€” in pa...,NaN

In [3]:
recom_data = coffee.filter(['name', 'aroma', 'acid', 'body', 'rating', 'roaster', 'desc_1', 'desc_2'])
values = {'roast': 'Unknown', 'aroma': 0.0, 'acid': 0.0, 'body': 0.0, 'flavor': 0.0, 'aftertaste': 0.0}
recom_data.fillna(values, inplace=True)
recom_data

,name,aroma,acid,body,rating,roaster,desc_1,desc_2
0,Ethiopia Deri Kochoha,9.0,8.0,9.0,93,Flight Coffee Co.,"Bright, crisp, sweetly tart. Citrus medley, ca...",From the Deri Kochoha mill in the Hagere Marya...
1,Espresso,8.0,0.0,8.0,91,Doi Chaang Coffee,"Evaluated as espresso. Deeply rich, sweetly ro...",Doi Chaang is a single-estate coffee produced ...
2,Kenya Ruthaka Peaberry,9.0,8.0,9.0,95,Temple Coffee and Tea,"Deeply sweet, richly savory. Dark chocolate, p...",Despite challenges ranging from contested gove...
3,Ethiopia Gora Kone Sidamo,9.0,8.0,9.0,93,Temple Coffee and Tea,"Fruit-forward, richly chocolaty. Raspberry cou...",Southern Ethiopia coffees like this one are la...
4,Specialty Coffee Blend Espresso,9.0,0.0,8.0,93,Choosy Gourmet,"Evaluated as espresso. Rich, chocolaty, sweetl...",A blend of coffees from Ethiopia (natural-proc...
...,...,...,...,...,...,...,...,...
5119,Beanery Blend,8.0,7.0,7.0,83,The Coffee Beanery,A light-medium-roasted blend with power: The a...,A light-medium-roasted blend with power: inten...
5120,House Blend,7.0,8.0,6.0,81,Starbucks Coffee,The rest of the taste profile plays peek-a-boo...,The rest of the taste profile plays peek-a-boo...
5121,Presidentâ€™s Private Blend,6.0,5.0,6.0,75,Peerless Coffee,"Given the medium roast, the carbon notes here ...",A medium roast with surprising carbon notes su...
5122,Traditional Roast,7.0,6.0,6.0,74,Gevalia,"For such a relatively light roast, not particu...",A classic American (light) roast profile thoug...
5123,Special Roast,5.0,5.0,4.0,68,CafÃ© Godiva,This coffee arrived pre-ground (not available ...,"Arrived pre-ground, perhaps accounting for fla..."

In [4]:
data = coffee.filter(['aroma', 'acid', 'body', 'name'])
data.head(5)

   aroma  acid  body                             name
0    9.0   8.0   9.0            Ethiopia Deri Kochoha
1    8.0   NaN   8.0                         Espresso
2    9.0   8.0   9.0           Kenya Ruthaka Peaberry
3    9.0   8.0   9.0        Ethiopia Gora Kone Sidamo
4    9.0   NaN   8.0  Specialty Coffee Blend Espresso

In [5]:
data.rename(columns=({'name':'label'}), inplace=True)
data.head(5)

   aroma  acid  body                            label
0    9.0   8.0   9.0            Ethiopia Deri Kochoha
1    8.0   NaN   8.0                         Espresso
2    9.0   8.0   9.0           Kenya Ruthaka Peaberry
3    9.0   8.0   9.0        Ethiopia Gora Kone Sidamo
4    9.0   NaN   8.0  Specialty Coffee Blend Espresso

#**Exploratory Data Analysis**

##**Handling Missing Value**

In [6]:
data.isnull().sum()

aroma     39
acid     868
body      13
label      0
dtype: int64

In [7]:
values = {'aroma': 0.0, 'acid': 0.0, 'body': 0.0}
data.fillna(values, inplace=True)

##**Data Analysis**

**Encode label**

In [8]:
labelEncoder = LabelEncoder()

labelEncoder.fit_transform(data["label"])
labelEncoder_key_value = dict(zip(labelEncoder.classes_, labelEncoder.transform(labelEncoder.classes_)))

data_encode = pd.DataFrame(labelEncoder_key_value.items(), columns=['Original Label', 'Encoded'])

In [9]:
data_encode.head(5)

                                      Original Label  Encoded
0                                   100 Percent Kona        0
1   100 Percent Kona Coffee Extra Fancy Medium Roast        1
2                        100 Percent Mexican Organic        2
3  100 Percent Puna Kazumura Reserve Peaberry Med...        3
4                                       100% Arabica        4

In [10]:
data['label'] = labelEncoder.transform(data['label'])
data

      aroma  acid  body  label
0       9.0   8.0   9.0   1321
1       8.0   0.0   8.0   1201
2       9.0   8.0   9.0   2600
3       9.0   8.0   9.0   1344
4       9.0   0.0   8.0   3789
...     ...   ...   ...    ...
5119    8.0   7.0   7.0    178
5120    7.0   8.0   6.0   2168
5121    6.0   5.0   6.0   3520
5122    7.0   6.0   6.0   4063
5123    5.0   5.0   4.0   3788

[5124 rows x 4 columns]

In [11]:
X = data.iloc[:, 0:-1]
y = data.iloc[:, -1]

In [12]:
model = svm.SVC()
model_2 = KNeighborsClassifier()
model_3 = RandomForestClassifier(n_estimators=100)

model.fit(X, y)
model_2.fit(X, y)
model_3.fit(X, y)

RandomForestClassifier()

In [13]:
model_3.fit(X.values, y)

RandomForestClassifier()

In [14]:
model_3.predict([[7.0, 6.0, 6.0]])

array([3904])

In [15]:
data_encode[data_encode['Encoded']==3904]

          Original Label  Encoded
3904  Sumatra Mandheling     3904

In [19]:
recom_data[(recom_data['name'] == 'Sumatra Mandheling') & (recom_data['aroma'] == 7.0) & (recom_data['acid'] == 6.0) & (recom_data['body'] == 6.0)]

,name,aroma,acid,body,rating,roaster,desc_1,desc_2
4862,Sumatra Mandheling,7.0,6.0,6.0,80,Alpen Sierra Coffee Roasters,Distinctive but limited. The strength of the c...,"Distinctive, but limited. Its strength is a po..."
4864,Sumatra Mandheling,7.0,6.0,6.0,79,The Coffee Roaster,"The roast dominates the coffee here, overlayin...","The roast dominates the coffee here, overlayin..."
4986,Sumatra Mandheling,7.0,6.0,6.0,80,Coffee Masters,An interesting but atypical Sumatra profile: D...,An interesting but atypical Sumatra profile: d...